config/routes.rb
Rails.application.routes.draw do
  root 'tasks#index'
  resources :tasks
  resources :users, only: [:new, :create, :show, :edit, :update, :destroy]
  resources :sessions, only: [:new, :create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true

  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
    validates :name, presence: true, length: { maximum: 30}
  validates :email, presence: true, length: { maximum: 255}, format: {with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i}
  before_validation { email.downcase!}
  validates :email, uniqueness: {message: 'はすでに使用されています'}
  validates :password, length: { minimum: 6 }, presence: true

  has_secure_password

  has_many :tasks, :dependent => :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include SessionsHelper
    before_action :login_required

    private
  
  def login_required
    redirect_to new_session_path, flash: {alert: "ログインしてください"} unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  
    def new
    end

    def create
        user = User.find_by(email: params[:session][:email].downcase)
        if user&.authenticate(params[:session][:password])
          log_in(user)
          flash[:notice] = 'ログインしました'
          redirect_to tasks_path
        else
          flash.now[:danger] = 'メールアドレスまたはパスワードに誤りがあります'
          render :new
        end
    end

    def destroy
      session.delete(:user_id)
      flash[:notice] = 'ログアウトしました'
      redirect_to new_session_path
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[ show edit update destroy ]

  def index
    @user = current_user
    @tasks = @user.tasks
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.user_id = current_user.id
    if @task.save
      redirect_to tasks_path, notice: t('.created')
    else
      render :new
    end
  end

  def show
  end

  def edit
  end

  def update
    if @task.update(task_params)
      redirect_to tasks_path, notice: t('.updated')
    else
      render :edit
    end
  end

  def destroy
    @task.destroy
    redirect_to tasks_path, notice: t('.destroyed')
  end

  private

    def set_task
      @task = Task.find(params[:id])
    end

    def task_params
      params.require(:task).permit(:title, :content)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  skip_before_action :login_required, only: [:new, :create]
  before_action :correct_user, only: [:show, :edit]

    def new
        @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        log_in(@user)
        flash[:notice] = 'アカウントを登録しました'
        redirect_to tasks_path
      else
        render :new
      end
    end

    def show
        @user = User.find(params[:id])
    end

    def edit
      @user = User.find(params[:id])
    end

    def update
      @user = User.find(params[:id])
      if @user.update(user_params)
        flash[:notice] = 'アカウントを更新しました'
        redirect_to user_path(@user.id)
      else
        render :edit
      end
    end

    def destroy
      @user = User.find(params[:id])
      @user.destroy
      flash[:notice] = 'アカウントを削除しました'
      redirect_to new_session_path
    end

    private

    def user_params
      params.require(:user).permit(:name, :email, :password, :password_confirmation)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to current_user unless current_user?(@user)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def current_user
        @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
      end
    
      def logged_in?
        current_user.present?
      end
    
      def log_in(user)
        session[:user_id] = user.id
      end
    
      def current_user?(user)
        user == current_user
      end
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CdpWebRailsSessionLoginTask</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <% flash.each do |key, value| %>
    <%= content_tag(:div, value, class: "#{key}") %>
  <% end %>
  <ul>
  <% if logged_in? %>
    <li><%= link_to "タスク一覧", tasks_path, id: "tasks-index" %></li>
    <li><%= link_to "タスクを登録する", new_task_path, id: "new-task" %></li>
    <li><%= link_to "アカウント", user_path(current_user.id), id: "my-account" %></li>
    <li><%= link_to "ログアウト", session_path(current_user.id), method: :delete, id: "sign-out"%></li>
  <% else %>
    <li><%= link_to "アカウント登録", new_user_path, id: "sign-up" %></li>
    <li><%= link_to "ログイン", new_session_path, id: "sign-in" %></li>
  <% end %>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_with(model: task, local: true) do |form| %>
  <% if task.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(task.errors.count, "error") %> prohibited this task from being saved:</h2>

      <ul>
        <% task.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/tasks/edit.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', task: @task %>

<%= link_to t('common.show'), @task %> |
<%= link_to t('common.back'), tasks_path %>

app/views/tasks/index.html.erb
<h1><%= t('.title') %></h1>

<table>
  <thead>
    <tr>
      <th><%= Task.human_attribute_name(:title) %></th>
      <th><%= Task.human_attribute_name(:content) %></th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
      <tr>
        <td><%= task.title %></td>
        <td><%= task.content %></td>
        <td><%= link_to t('common.show'), task %></td>
        <td><%= link_to t('common.edit'), edit_task_path(task) %></td>
        <td><%= link_to t('common.destroy'), task, method: :delete, data: { confirm: t('common.confirm_destroy') } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to t('common.new'), new_task_path %>

app/views/tasks/new.html.erb
<h1><%= t('.title') %></h1>

<%= render 'form', task: @task %>

<%= link_to t('common.back'), tasks_path %>

app/views/tasks/show.html.erb
<h1><%= t('.title') %></h1>

<p>
  <strong><%= Task.human_attribute_name(:title) %>:</strong>
  <%= @task.title %>
</p>

<p>
  <strong><%= Task.human_attribute_name(:content) %>:</strong>
  <%= @task.content %>
</p>

<%= link_to t('common.edit'), edit_task_path(@task) %> |
<%= link_to t('common.back'), tasks_path %>

app/views/users/edit.html.erb
<h1>アカウント編集ページ</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %> 件のエラーのため、アカウントを更新できません。 </h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name %>
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email %>
  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "パスワード(確認)" %>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit "登録する" %>
<% end %>
<%= link_to "戻る", tasks_path, id: "back" %>

app/views/users/new.html.erb
<h1>アカウント登録ページ</h1>
<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= @user.errors.count %> 件のエラーのため、アカウント作成ができません。 </h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name, "名前" %>
  <%= f.text_field :name %>
  <%= f.label :email, "メールアドレス" %>
  <%= f.email_field :email %>
  <%= f.label :password, "パスワード" %>
  <%= f.password_field :password %>
  <%= f.label :password_confirmation, "パスワード(確認)" %>
  <%= f.password_field :password_confirmation %><br><br>
  <%= f.submit "登録する" %>
<% end %>

app/views/users/show.html.erb
<h1>アカウント詳細ページ</h1>
<p>名前: <%= @user.name %></p>
<p>メールアドレス: <%= @user.email %></p>

<%= link_to "編集", edit_user_path(@user.id) %>
|
<%= link_to "削除", user_path(current_user.id), method: :delete, data: { confirm: '本当に削除してもよろしいですか?'} %>